all: zip

zip: clean
	zip -r submission.zip structures/m_extensible_list.py structures/m_single_linked_list.py structures/m_stack.py test_structures.py execute_refgrid.py statement.txt

clean: 
	rm -rf submission.zip
